<?php

namespace Database\Seeders;

use App\Models\DailyActivity;
use App\Models\GameSession;
use App\Models\User;
use App\Models\Level;
use App\Models\Word;
use App\Models\Ranking;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Limpa as tabelas para garantir um novo começo limpo
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Word::truncate();
        Ranking::truncate();
        GameSession::truncate();
        DailyActivity::truncate();
        Level::truncate();
        User::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // --- CRIAÇÃO DE USUÁRIOS ---
        User::factory()->create(['name' => 'Jogador Teste', 'email' => 'jogador@teste.com', 'password' => Hash::make('123456')]);
        User::factory(10)->create()->each(fn($user) => Ranking::factory()->create(['user_id' => $user->id]));

        // --- CRIAÇÃO DOS NÍVEIS COM A NOVA CURVA DE DIFICULDADE ---
        for ($i = 1; $i <= 100; $i++) {
            Level::create([
                'level_number' => $i,
                // Tabuleiro começa em 8x8 e aumenta 1 a cada 10 níveis
                'grid_size' => 8 + floor(($i - 1) / 10),
                // Tempo começa em 90s e aumenta 1s por nível
                'time_limit_seconds' => 90 + $i,
            ]);
        }

        // --- ARRAY DE VOCABULÁRIO COM 1000 PALAVRAS E ÍCONES ---

        $vocabulary = [
            // Animais (100)
            ['word' => 'ANT', 'translation' => 'FORMIGA', 'icon' => '🐜'],
            ['word' => 'BAT', 'translation' => 'MORCEGO', 'icon' => '🦇'],
            ['word' => 'BEAR', 'translation' => 'URSO', 'icon' => '🐻'],
            ['word' => 'BEE', 'translation' => 'ABELHA', 'icon' => '🐝'],
            ['word' => 'BIRD', 'translation' => 'PÁSSARO', 'icon' => '🐦'],
            ['word' => 'BUG', 'translation' => 'INSETO', 'icon' => '🐛'],
            ['word' => 'BUTTERFLY', 'translation' => 'BORBOLETA', 'icon' => '🦋'],
            ['word' => 'CAMEL', 'translation' => 'CAMELO', 'icon' => '🐫'],
            ['word' => 'CAT', 'translation' => 'GATO', 'icon' => '🐱'],
            ['word' => 'CHICKEN', 'translation' => 'GALINHA', 'icon' => '🐔'],
            ['word' => 'COW', 'translation' => 'VACA', 'icon' => '🐮'],
            ['word' => 'CRAB', 'translation' => 'CARANGUEJO', 'icon' => '🦀'],
            ['word' => 'CROCODILE', 'translation' => 'CROCODILO', 'icon' => '🐊'],
            ['word' => 'DEER', 'translation' => 'CERVO', 'icon' => '🦌'],
            ['word' => 'DOG', 'translation' => 'CÃO', 'icon' => '🐶'],
            ['word' => 'DOLPHIN', 'translation' => 'GOLFINHO', 'icon' => '🐬'],
            ['word' => 'DONKEY', 'translation' => 'BURRO', 'icon' => '🐴'],
            ['word' => 'DUCK', 'translation' => 'PATO', 'icon' => '🦆'],
            ['word' => 'EAGLE', 'translation' => 'ÁGUIA', 'icon' => '🦅'],
            ['word' => 'ELEPHANT', 'translation' => 'ELEFANTE', 'icon' => '🐘'],
            ['word' => 'FISH', 'translation' => 'PEIXE', 'icon' => '🐟'],
            ['word' => 'FLY', 'translation' => 'MOSCA', 'icon' => '🪰'],
            ['word' => 'FOX', 'translation' => 'RAPOSA', 'icon' => '🦊'],
            ['word' => 'FROG', 'translation' => 'SAPO', 'icon' => '🐸'],
            ['word' => 'GIRAFFE', 'translation' => 'GIRAFA', 'icon' => '🦒'],
            ['word' => 'GOAT', 'translation' => 'CABRA', 'icon' => '🐐'],
            ['word' => 'GORILLA', 'translation' => 'GORILA', 'icon' => '🦍'],
            ['word' => 'HAMSTER', 'translation' => 'HAMSTER', 'icon' => '🐹'],
            ['word' => 'HEDGEHOG', 'translation' => 'OURIÇO', 'icon' => '🦔'],
            ['word' => 'HIPPO', 'translation' => 'HIPOPÓTAMO', 'icon' => '🦛'],
            ['word' => 'HORSE', 'translation' => 'CAVALO', 'icon' => '🐴'],
            ['word' => 'KANGAROO', 'translation' => 'CANGURU', 'icon' => '🦘'],
            ['word' => 'KOALA', 'translation' => 'COALA', 'icon' => '🐨'],
            ['word' => 'LEOPARD', 'translation' => 'LEOPARDO', 'icon' => '🐆'],
            ['word' => 'LION', 'translation' => 'LEÃO', 'icon' => '🦁'],
            ['word' => 'LIZARD', 'translation' => 'LAGARTO', 'icon' => '🦎'],
            ['word' => 'LLAMA', 'translation' => 'LHAMA', 'icon' => '🦙'],
            ['word' => 'MONKEY', 'translation' => 'MACACO', 'icon' => '🐵'],
            ['word' => 'MOSQUITO', 'translation' => 'MOSQUITO', 'icon' => '🦟'],
            ['word' => 'MOUSE', 'translation' => 'RATO', 'icon' => '🐭'],
            ['word' => 'OCTOPUS', 'translation' => 'POLVO', 'icon' => '🐙'],
            ['word' => 'OTTER', 'translation' => 'LONTRA', 'icon' => '🦦'],
            ['word' => 'OWL', 'translation' => 'CORUJA', 'icon' => '🦉'],
            ['word' => 'OX', 'translation' => 'BOI', 'icon' => '🐂'],
            ['word' => 'PANDA', 'translation' => 'PANDA', 'icon' => '🐼'],
            ['word' => 'PARROT', 'translation' => 'PAPAGAIO', 'icon' => '🦜'],
            ['word' => 'PEACOCK', 'translation' => 'PAVÃO', 'icon' => '🦚'],
            ['word' => 'PENGUIN', 'translation' => 'PINGUIM', 'icon' => '🐧'],
            ['word' => 'PIG', 'translation' => 'PORCO', 'icon' => '🐷'],
            ['word' => 'PIGEON', 'translation' => 'POMBO', 'icon' => '🕊️'],
            ['word' => 'RABBIT', 'translation' => 'COELHO', 'icon' => '🐰'],
            ['word' => 'RACCOON', 'translation' => 'GUAXINIM', 'icon' => '🦝'],
            ['word' => 'RAT', 'translation' => 'RATAZANA', 'icon' => '🐀'],
            ['word' => 'RHINO', 'translation' => 'RINOCERONTE', 'icon' => '🦏'],
            ['word' => 'ROOSTER', 'translation' => 'GALO', 'icon' => '🐓'],
            ['word' => 'SEAL', 'translation' => 'FOCA', 'icon' => '🦭'],
            ['word' => 'SHARK', 'translation' => 'TUBARÃO', 'icon' => '🦈'],
            ['word' => 'SHEEP', 'translation' => 'OVELHA', 'icon' => '🐑'],
            ['word' => 'SHRIMP', 'translation' => 'CAMARÃO', 'icon' => '🦐'],
            ['word' => 'SKUNK', 'translation' => 'GAMBÁ', 'icon' => '🦨'],
            ['word' => 'SLOTH', 'translation' => 'PREGUIÇA', 'icon' => '🦥'],
            ['word' => 'SNAIL', 'translation' => 'CARACOL', 'icon' => '🐌'],
            ['word' => 'SNAKE', 'translation' => 'COBRA', 'icon' => '🐍'],
            ['word' => 'SPIDER', 'translation' => 'ARANHA', 'icon' => '🕷️'],
            ['word' => 'SQUID', 'translation' => 'LULA', 'icon' => '🦑'],
            ['word' => 'SQUIRREL', 'translation' => 'ESQUILO', 'icon' => '🐿️'],
            ['word' => 'SWAN', 'translation' => 'CISNE', 'icon' => '🦢'],
            ['word' => 'TIGER', 'translation' => 'TIGRE', 'icon' => '🐯'],
            ['word' => 'TURKEY', 'translation' => 'PERU', 'icon' => '🦃'],
            ['word' => 'TURTLE', 'translation' => 'TARTARUGA', 'icon' => '🐢'],
            ['word' => 'WHALE', 'translation' => 'BALEIA', 'icon' => '🐳'],
            ['word' => 'WOLF', 'translation' => 'LOBO', 'icon' => '🐺'],
            ['word' => 'WORM', 'translation' => 'MINHOCA', 'icon' => '🪱'],
            ['word' => 'ZEBRA', 'translation' => 'ZEBRA', 'icon' => '🦓'],
            ['word' => 'BISON', 'translation' => 'BISÃO', 'icon' => '🦬'],
            ['word' => 'BOAR', 'translation' => 'JAVALI', 'icon' => '🐗'],
            ['word' => 'BADGER', 'translation' => 'TEXUGO', 'icon' => '🦡'],
            ['word' => 'BEAVER', 'translation' => 'CASTOR', 'icon' => '🦫'],
            ['word' => 'CHIPMUNK', 'translation' => 'TÂMIA', 'icon' => '🐿️'],
            ['word' => 'CRICKET', 'translation' => 'GRILO', 'icon' => '🦗'],
            ['word' => 'FLAMINGO', 'translation' => 'FLAMINGO', 'icon' => '🦩'],
            ['word' => 'GOOSE', 'translation' => 'GANSO', 'icon' => '🦢'],
            ['word' => 'HAWK', 'translation' => 'FALCÃO', 'icon' => '🦅'],
            ['word' => 'JELLYFISH', 'translation' => 'ÁGUA-VIVA', 'icon' => '🪼'],
            ['word' => 'LADYBUG', 'translation' => 'JOANINHA', 'icon' => '🐞'],
            ['word' => 'MAMMOTH', 'translation' => 'MAMUTE', 'icon' => '🦣'],
            ['word' => 'MOOSE', 'translation' => 'ALCE', 'icon' => '🦌'],
            ['word' => 'ORCA', 'translation' => 'ORCA', 'icon' => '🐳'],
            ['word' => 'OSTRICH', 'translation' => 'AVESTRUZ', 'icon' => '🦚'],
            ['word' => 'PELICAN', 'translation' => 'PELICANO', 'icon' => '🐦'],
            ['word' => 'PORCUPINE', 'translation' => 'PORCO-ESPINHO', 'icon' => '🦔'],
            ['word' => 'PUFFERFISH', 'translation' => 'BAIACU', 'icon' => '🐡'],
            ['word' => 'SCORPION', 'translation' => 'ESCORPIÃO', 'icon' => '🦂'],
            ['word' => 'SEAGULL', 'translation' => 'GAIVOTA', 'icon' => '🐦'],
            ['word' => 'STARFISH', 'translation' => 'ESTRELA DO MAR', 'icon' => '⭐'],
            ['word' => 'STINGRAY', 'translation' => 'ARRAIA', 'icon' => '🐟'],
            ['word' => 'VULTURE', 'translation' => 'ABUTRE', 'icon' => '🦅'],
            ['word' => 'WALRUS', 'translation' => 'MORSA', 'icon' => '🦭'],
            // Comida e Bebida (100)
            ['word' => 'APPLE', 'translation' => 'MAÇÃ', 'icon' => '🍎'],
            ['word' => 'AVOCADO', 'translation' => 'ABACATE', 'icon' => '🥑'],
            ['word' => 'BACON', 'translation' => 'BACON', 'icon' => '🥓'],
            ['word' => 'BAGUETTE', 'translation' => 'BAGUETE', 'icon' => '🥖'],
            ['word' => 'BANANA', 'translation' => 'BANANA', 'icon' => '🍌'],
            ['word' => 'BEANS', 'translation' => 'FEIJÃO', 'icon' => '🫘'],
            ['word' => 'BEER', 'translation' => 'CERVEJA', 'icon' => '🍺'],
            ['word' => 'BLUEBERRY', 'translation' => 'MIRTILO', 'icon' => '🫐'],
            ['word' => 'BREAD', 'translation' => 'PÃO', 'icon' => '🍞'],
            ['word' => 'BROCCOLI', 'translation' => 'BRÓCOLIS', 'icon' => '🥦'],
            ['word' => 'BURGER', 'translation' => 'HAMBÚRGUER', 'icon' => '🍔'],
            ['word' => 'BURRITO', 'translation' => 'BURRITO', 'icon' => '🌯'],
            ['word' => 'BUTTER', 'translation' => 'MANTEIGA', 'icon' => '🧈'],
            ['word' => 'CAKE', 'translation' => 'BOLO', 'icon' => '🎂'],
            ['word' => 'CANDY', 'translation' => 'DOCE', 'icon' => '🍬'],
            ['word' => 'CARROT', 'translation' => 'CENOURA', 'icon' => '🥕'],
            ['word' => 'CHEESE', 'translation' => 'QUEIJO', 'icon' => '🧀'],
            ['word' => 'CHERRY', 'translation' => 'CEREJA', 'icon' => '🍒'],
            ['word' => 'CHOCOLATE', 'translation' => 'CHOCOLATE', 'icon' => '🍫'],
            ['word' => 'COCONUT', 'translation' => 'COCO', 'icon' => '🥥'],
            ['word' => 'COFFEE', 'translation' => 'CAFÉ', 'icon' => '☕'],
            ['word' => 'COOKIE', 'translation' => 'BISCOITO', 'icon' => '🍪'],
            ['word' => 'CORN', 'translation' => 'MILHO', 'icon' => '🌽'],
            ['word' => 'CROISSANT', 'translation' => 'CROISSANT', 'icon' => '🥐'],
            ['word' => 'CUCUMBER', 'translation' => 'PEPINO', 'icon' => '🥒'],
            ['word' => 'CUPCAKE', 'translation' => 'CUPCAKE', 'icon' => '🧁'],
            ['word' => 'CURRY', 'translation' => 'CARIL', 'icon' => '🍛'],
            ['word' => 'DONUT', 'translation' => 'ROSQUINHA', 'icon' => '🍩'],
            ['word' => 'DUMPLING', 'translation' => 'BOLINHO', 'icon' => '🥟'],
            ['word' => 'EGG', 'translation' => 'OVO', 'icon' => '🥚'],
            ['word' => 'EGGPLANT', 'translation' => 'BERINJELA', 'icon' => '🍆'],
            ['word' => 'FRIES', 'translation' => 'BATATAS FRITAS', 'icon' => '🍟'],
            ['word' => 'GARLIC', 'translation' => 'ALHO', 'icon' => '🧄'],
            ['word' => 'GRAPE', 'translation' => 'UVA', 'icon' => '🍇'],
            ['word' => 'HONEY', 'translation' => 'MEL', 'icon' => '🍯'],
            ['word' => 'HOTDOG', 'translation' => 'CACHORRO-QUENTE', 'icon' => '🌭'],
            ['word' => 'ICECREAM', 'translation' => 'SORVETE', 'icon' => '🍦'],
            ['word' => 'JUICE', 'translation' => 'SUCO', 'icon' => '🧃'],
            ['word' => 'KIWI', 'translation' => 'KIWI', 'icon' => '🥝'],
            ['word' => 'LEMON', 'translation' => 'LIMÃO', 'icon' => '🍋'],
            ['word' => 'LETTUCE', 'translation' => 'ALFACE', 'icon' => '🥬'],
            ['word' => 'MANGO', 'translation' => 'MANGA', 'icon' => '🥭'],
            ['word' => 'MEAT', 'translation' => 'CARNE', 'icon' => '🥩'],
            ['word' => 'MELON', 'translation' => 'MELÃO', 'icon' => '🍈'],
            ['word' => 'MILK', 'translation' => 'LEITE', 'icon' => '🥛'],
            ['word' => 'MUSHROOM', 'translation' => 'COGUMELO', 'icon' => '🍄'],
            ['word' => 'NOODLE', 'translation' => 'MACARRÃO', 'icon' => '🍜'],
            ['word' => 'OLIVE', 'translation' => 'AZEITONA', 'icon' => '🫒'],
            ['word' => 'ONION', 'translation' => 'CEBOLA', 'icon' => '🧅'],
            ['word' => 'ORANGE', 'translation' => 'LARANJA', 'icon' => '🍊'],
            ['word' => 'PANCAKE', 'translation' => 'PANQUECA', 'icon' => '🥞'],
            ['word' => 'PEACH', 'translation' => 'PÊSSEGO', 'icon' => '🍑'],
            ['word' => 'PEANUT', 'translation' => 'AMENDOIM', 'icon' => '🥜'],
            ['word' => 'PEAR', 'translation' => 'PERA', 'icon' => '🍐'],
            ['word' => 'PEPPER', 'translation' => 'PIMENTÃO', 'icon' => '🌶️'],
            ['word' => 'PIE', 'translation' => 'TORTA', 'icon' => '🥧'],
            ['word' => 'PINEAPPLE', 'translation' => 'ABACAXI', 'icon' => '🍍'],
            ['word' => 'PIZZA', 'translation' => 'PIZZA', 'icon' => '🍕'],
            ['word' => 'POPCORN', 'translation' => 'PIPOCA', 'icon' => '🍿'],
            ['word' => 'POTATO', 'translation' => 'BATATA', 'icon' => '🥔'],
            ['word' => 'PRETZEL', 'translation' => 'PRETZEL', 'icon' => '🥨'],
            ['word' => 'PUMPKIN', 'translation' => 'ABÓBORA', 'icon' => '🎃'],
            ['word' => 'RICE', 'translation' => 'ARROZ', 'icon' => '🍚'],
            ['word' => 'SALAD', 'translation' => 'SALADA', 'icon' => '🥗'],
            ['word' => 'SALT', 'translation' => 'SAL', 'icon' => '🧂'],
            ['word' => 'SANDWICH', 'translation' => 'SANDUÍCHE', 'icon' => '🥪'],
            ['word' => 'SHRIMP', 'translation' => 'CAMARÃO', 'icon' => '🦐'],
            ['word' => 'SOUP', 'translation' => 'SOPA', 'icon' => '🍲'],
            ['word' => 'SPAGHETTI', 'translation' => 'ESPAGUETE', 'icon' => '🍝'],
            ['word' => 'STEAK', 'translation' => 'BIFE', 'icon' => '🥩'],
            ['word' => 'STRAWBERRY', 'translation' => 'MORANGO', 'icon' => '🍓'],
            ['word' => 'SUGAR', 'translation' => 'AÇÚCAR', 'icon' => '🍬'],
            ['word' => 'SUSHI', 'translation' => 'SUSHI', 'icon' => '🍣'],
            ['word' => 'TACO', 'translation' => 'TACO', 'icon' => '🌮'],
            ['word' => 'TEA', 'translation' => 'CHÁ', 'icon' => '🫖'],
            ['word' => 'TOMATO', 'translation' => 'TOMATE', 'icon' => '🍅'],
            ['word' => 'WAFFLE', 'translation' => 'WAFFLE', 'icon' => '🧇'],
            ['word' => 'WATERMELON', 'translation' => 'MELANCIA', 'icon' => '🍉'],
            ['word' => 'WINE', 'translation' => 'VINHO', 'icon' => '🍷'],
            ['word' => 'ALMOND', 'translation' => 'AMÊNDOA', 'icon' => '🥜'],
            ['word' => 'ARTICHOKE', 'translation' => 'ALCACHOFRA', 'icon' => '🥬'],
            ['word' => 'ASPARAGUS', 'translation' => 'ASPARGO', 'icon' => '🥬'],
            ['word' => 'BENTO', 'translation' => 'BENTÔ', 'icon' => '🍱'],
            ['word' => 'BEVERAGE', 'translation' => 'BEBIDA', 'icon' => '🥤'],
            ['word' => 'BOWL', 'translation' => 'TIGELA', 'icon' => '🥣'],
            ['word' => 'CABBAGE', 'translation' => 'REPOlHO', 'icon' => '🥬'],
            ['word' => 'CHOPSTICKS', 'translation' => 'HASHI', 'icon' => '🥢'],
            ['word' => 'CINNAMON', 'translation' => 'CANELA', 'icon' => '🌿'],
            ['word' => 'COCKTAIL', 'translation' => 'COQUETEL', 'icon' => '🍸'],
            ['word' => 'FALAFEL', 'translation' => 'FALAFEL', 'icon' => '🧆'],
            ['word' => 'FLOUR', 'translation' => 'FARINHA', 'icon' => '🌾'],
            ['word' => 'FONDUE', 'translation' => 'FONDUE', 'icon' => '🫕'],
            ['word' => 'GINGER', 'translation' => 'GENGIBRE', 'icon' => '🫚'],
            ['word' => 'LOBSTER', 'translation' => 'LAGOSTA', 'icon' => '🦞'],
            ['word' => 'OYSTER', 'translation' => 'OSTRA', 'icon' => '🦪'],
            ['word' => 'PASTA', 'translation' => 'MASSA', 'icon' => '🍝'],
            ['word' => 'SYRUP', 'translation' => 'XAROPE', 'icon' => '🍁'],
            // Lugares e Natureza (100)
            ['word' => 'BEACH', 'translation' => 'PRAIA', 'icon' => '🏖️'],
            ['word' => 'BRIDGE', 'translation' => 'PONTE', 'icon' => '🌉'],
            ['word' => 'BUILDING', 'translation' => 'PRÉDIO', 'icon' => '🏢'],
            ['word' => 'CASTLE', 'translation' => 'CASTELO', 'icon' => '🏰'],
            ['word' => 'CAVE', 'translation' => 'CAVERNA', 'icon' => '⛰️'],
            ['word' => 'CHURCH', 'translation' => 'IGREJA', 'icon' => '⛪'],
            ['word' => 'CINEMA', 'translation' => 'CINEMA', 'icon' => '🎬'],
            ['word' => 'CITY', 'translation' => 'CIDADE', 'icon' => '🏙️'],
            ['word' => 'CLOUD', 'translation' => 'NUVEM', 'icon' => '☁️'],
            ['word' => 'COUNTRY', 'translation' => 'PAÍS', 'icon' => '🗺️'],
            ['word' => 'DESERT', 'translation' => 'DESERTO', 'icon' => '🏜️'],
            ['word' => 'EARTH', 'translation' => 'TERRA', 'icon' => '🌍'],
            ['word' => 'FACTORY', 'translation' => 'FÁBRICA', 'icon' => '🏭'],
            ['word' => 'FARM', 'translation' => 'FAZENDA', 'icon' => '🚜'],
            ['word' => 'FIELD', 'translation' => 'CAMPO', 'icon' => '🌾'],
            ['word' => 'FIRE', 'translation' => 'FOGO', 'icon' => '🔥'],
            ['word' => 'FLOWER', 'translation' => 'FLOR', 'icon' => '🌸'],
            ['word' => 'FOREST', 'translation' => 'FLORESTA', 'icon' => '🌳'],
            ['word' => 'FOUNTAIN', 'translation' => 'FONTE', 'icon' => '⛲'],
            ['word' => 'GALAXY', 'translation' => 'GALÁXIA', 'icon' => '🌌'],
            ['word' => 'GARDEN', 'translation' => 'JARDIM', 'icon' => '🪴'],
            ['word' => 'HILL', 'translation' => 'COLINA', 'icon' => '⛰️'],
            ['word' => 'HOSPITAL', 'translation' => 'HOSPITAL', 'icon' => '🏥'],
            ['word' => 'HOTEL', 'translation' => 'HOTEL', 'icon' => '🏨'],
            ['word' => 'HOUSE', 'translation' => 'CASA', 'icon' => '🏠'],
            ['word' => 'ISLAND', 'translation' => 'ILHA', 'icon' => '🏝️'],
            ['word' => 'JUNGLE', 'translation' => 'SELVA', 'icon' => '🌳'],
            ['word' => 'LAKE', 'translation' => 'LAGO', 'icon' => '🏞️'],
            ['word' => 'LAND', 'translation' => 'TERRA', 'icon' => '🌍'],
            ['word' => 'LEAF', 'translation' => 'FOLHA', 'icon' => '🍃'],
            ['word' => 'LIBRARY', 'translation' => 'BIBLIOTECA', 'icon' => '📚'],
            ['word' => 'LIGHTNING', 'translation' => 'RELÂMPAGO', 'icon' => '⚡'],
            ['word' => 'MARKET', 'translation' => 'MERCADO', 'icon' => '🏪'],
            ['word' => 'MOON', 'translation' => 'LUA', 'icon' => '🌙'],
            ['word' => 'MOUNTAIN', 'translation' => 'MONTANHA', 'icon' => '⛰️'],
            ['word' => 'MUSEUM', 'translation' => 'MUSEU', 'icon' => '🏛️'],
            ['word' => 'NATURE', 'translation' => 'NATUREZA', 'icon' => '🌿'],
            ['word' => 'OCEAN', 'translation' => 'OCEANO', 'icon' => '🌊'],
            ['word' => 'OFFICE', 'translation' => 'ESCRITÓRIO', 'icon' => '💼'],
            ['word' => 'PALACE', 'translation' => 'PALÁCIO', 'icon' => '🏰'],
            ['word' => 'PARK', 'translation' => 'PARQUE', 'icon' => '🏞️'],
            ['word' => 'PLANET', 'translation' => 'PLANETA', 'icon' => '🪐'],
            ['word' => 'PLANT', 'translation' => 'PLANTA', 'icon' => '🌱'],
            ['word' => 'RAIN', 'translation' => 'CHUVA', 'icon' => '🌧️'],
            ['word' => 'RAINBOW', 'translation' => 'ARCO-ÍRIS', 'icon' => '🌈'],
            ['word' => 'RIVER', 'translation' => 'RIO', 'icon' => '🏞️'],
            ['word' => 'ROAD', 'translation' => 'ESTRADA', 'icon' => '🛣️'],
            ['word' => 'ROCK', 'translation' => 'ROCHA', 'icon' => '🪨'],
            ['word' => 'ROOT', 'translation' => 'RAIZ', 'icon' => '🌱'],
            ['word' => 'SAND', 'translation' => 'AREIA', 'icon' => '🏖️'],
            ['word' => 'SCHOOL', 'translation' => 'ESCOLA', 'icon' => '🏫'],
            ['word' => 'SEA', 'translation' => 'MAR', 'icon' => '🌊'],
            ['word' => 'SKY', 'translation' => 'CÉU', 'icon' => '☁️'],
            ['word' => 'SNOW', 'translation' => 'NEVE', 'icon' => '❄️'],
            ['word' => 'STADIUM', 'translation' => 'ESTÁDIO', 'icon' => '🏟️'],
            ['word' => 'STAR', 'translation' => 'ESTRELA', 'icon' => '⭐'],
            ['word' => 'STATION', 'translation' => 'ESTAÇÃO', 'icon' => '🚉'],
            ['word' => 'STONE', 'translation' => 'PEDRA', 'icon' => '🪨'],
            ['word' => 'STORE', 'translation' => 'LOJA', 'icon' => '🏪'],
            ['word' => 'STREET', 'translation' => 'RUA', 'icon' => '🛣️'],
            ['word' => 'SUN', 'translation' => 'SOL', 'icon' => '☀️'],
            ['word' => 'SUNFLOWER', 'translation' => 'GIRASSOL', 'icon' => '🌻'],
            ['word' => 'SUNRISE', 'translation' => 'NAScer do SOL', 'icon' => '🌅'],
            ['word' => 'SUNSET', 'translation' => 'PÔR DO SOL', 'icon' => '🌇'],
            ['word' => 'TEMPLE', 'translation' => 'TEMPLO', 'icon' => '🏛️'],
            ['word' => 'TENT', 'translation' => 'BARRACA', 'icon' => '⛺'],
            ['word' => 'TOWN', 'translation' => 'CIDADE', 'icon' => '🏘️'],
            ['word' => 'TRAIN', 'translation' => 'TREM', 'icon' => '🚆'],
            ['word' => 'TREE', 'translation' => 'ÁRVORE', 'icon' => '🌳'],
            ['word' => 'TUNNEL', 'translation' => 'TÚNEL', 'icon' => '🚇'],
            ['word' => 'UNIVERSE', 'translation' => 'UNIVERSO', 'icon' => '🌌'],
            ['word' => 'VALLEY', 'translation' => 'VALE', 'icon' => '🏞️'],
            ['word' => 'VILLAGE', 'translation' => 'VILA', 'icon' => '🏘️'],
            ['word' => 'VOLCANO', 'translation' => 'VULCÃO', 'icon' => '🌋'],
            ['word' => 'WATERFALL', 'translation' => 'CACHOEIRA', 'icon' => '🏞️'],
            ['word' => 'WAVE', 'translation' => 'ONDA', 'icon' => '🌊'],
            ['word' => 'WIND', 'translation' => 'VENTO', 'icon' => '💨'],
            ['word' => 'WOOD', 'translation' => 'MADEIRA', 'icon' => '🪵'],
            ['word' => 'WORLD', 'translation' => 'MUNDO', 'icon' => '🌍'],
            ['word' => 'AIRPORT', 'translation' => 'AEROPORTO', 'icon' => '✈️'],
            ['word' => 'AQUARIUM', 'translation' => 'AQUÁRIO', 'icon' => '🐠'],
            ['word' => 'BAKERY', 'translation' => 'PADARIA', 'icon' => '🥖'],
            ['word' => 'BANK', 'translation' => 'BANCO', 'icon' => '🏦'],
            ['word' => 'BARN', 'translation' => 'CELEIRO', 'icon' => '헛'],
            ['word' => 'CACTUS', 'translation' => 'CACTO', 'icon' => '🌵'],
            ['word' => 'CAMPFIRE', 'translation' => 'FOGUEIRA', 'icon' => '🔥'],
            ['word' => 'CANYON', 'translation' => 'CÂNION', 'icon' => '🏞️'],
            ['word' => 'CARNIVAL', 'translation' => 'CARNAVAL', 'icon' => '🎡'],
            ['word' => 'CLOVER', 'translation' => 'TREVO', 'icon' => '🍀'],
            ['word' => 'COAST', 'translation' => 'COSTA', 'icon' => '🌊'],
            ['word' => 'COMET', 'translation' => 'COMETA', 'icon' => '☄️'],
            ['word' => 'DAM', 'translation' => 'REPRESA', 'icon' => '🏞️'],
            ['word' => 'DUNE', 'translation' => 'DUNA', 'icon' => '🏜️'],
            ['word' => 'FOG', 'translation' => 'NÉVOA', 'icon' => '🌫️'],
            ['word' => 'GEYSER', 'translation' => 'GÊISER', 'icon' => '🌋'],
            ['word' => 'GLACIER', 'translation' => 'Geleira', 'icon' => '🧊'],
            ['word' => 'GRASS', 'translation' => 'GRAMA', 'icon' => '🌿'],
            ['word' => 'HARBOR', 'translation' => 'PORTO', 'icon' => '⚓'],
            ['word' => 'HUT', 'translation' => 'CABANA', 'icon' => '🛖'],
            ['word' => 'ICEBERG', 'translation' => 'ICEBERG', 'icon' => '🧊'],
            ['word' => 'LIGHTHOUSE', 'translation' => 'FAROL', 'icon' => '💡'],
            // Objetos (100)
            ['word' => 'BALL', 'translation' => 'BOLA', 'icon' => '⚽'],
            ['word' => 'BALLOON', 'translation' => 'BALÃO', 'icon' => '🎈'],
            ['word' => 'BANDAGE', 'translation' => 'BANDAGEM', 'icon' => '🩹'],
            ['word' => 'BARREL', 'translation' => 'BARRIL', 'icon' => '🛢️'],
            ['word' => 'BASKET', 'translation' => 'CESTA', 'icon' => '🧺'],
            ['word' => 'BATTERY', 'translation' => 'BATERIA', 'icon' => '🔋'],
            ['word' => 'BED', 'translation' => 'CAMA', 'icon' => '🛏️'],
            ['word' => 'BELL', 'translation' => 'SINO', 'icon' => '🔔'],
            ['word' => 'BELT', 'translation' => 'CINTO', 'icon' => '띠'],
            ['word' => 'BICYCLE', 'translation' => 'BICICLETA', 'icon' => '🚲'],
            ['word' => 'BINOCULARS', 'translation' => 'BINÓCULOS', 'icon' => '🔭'],
            ['word' => 'BLANKET', 'translation' => 'COBERTOR', 'icon' => '🛌'],
            ['word' => 'BOARD', 'translation' => 'QUADRO', 'icon' => '칠판'],
            ['word' => 'BOAT', 'translation' => 'BARCO', 'icon' => '⛵'],
            ['word' => 'BOMB', 'translation' => 'BOMBA', 'icon' => '💣'],
            ['word' => 'BONE', 'translation' => 'OSSO', 'icon' => '🦴'],
            ['word' => 'BOOK', 'translation' => 'LIVRO', 'icon' => '📖'],
            ['word' => 'BOOT', 'translation' => 'BOTA', 'icon' => '👢'],
            ['word' => 'BOTTLE', 'translation' => 'GARRAFA', 'icon' => '🍾'],
            ['word' => 'BOW', 'translation' => 'ARCO', 'icon' => '🏹'],
            ['word' => 'BOWL', 'translation' => 'TIGELA', 'icon' => '🥣'],
            ['word' => 'BOX', 'translation' => 'CAIXA', 'icon' => '📦'],
            ['word' => 'BRACELET', 'translation' => 'PULSEIRA', 'icon' => '💍'],
            ['word' => 'BRICK', 'translation' => 'TIJOLO', 'icon' => '🧱'],
            ['word' => 'BROOM', 'translation' => 'VASSOURA', 'icon' => '🧹'],
            ['word' => 'BRUSH', 'translation' => 'ESCOVA', 'icon' => '🖌️'],
            ['word' => 'BUCKET', 'translation' => 'BALDE', 'icon' => '🪣'],
            ['word' => 'BULB', 'translation' => 'LÂMPADA', 'icon' => '💡'],
            ['word' => 'BUS', 'translation' => 'ÔNIBUS', 'icon' => '🚌'],
            ['word' => 'BUTTON', 'translation' => 'BOTÃO', 'icon' => '🔘'],
            ['word' => 'CALENDAR', 'translation' => 'CALENDÁRIO', 'icon' => '📅'],
            ['word' => 'CAMERA', 'translation' => 'CÂMERA', 'icon' => '📷'],
            ['word' => 'CANDLE', 'translation' => 'VELA', 'icon' => '🕯️'],
            ['word' => 'CAR', 'translation' => 'CARRO', 'icon' => '🚗'],
            ['word' => 'CARD', 'translation' => 'CARTA', 'icon' => '🃏'],
            ['word' => 'CARPET', 'translation' => 'TAPETE', 'icon' => '융단'],
            ['word' => 'CEILING', 'translation' => 'TETO', 'icon' => '🏠'],
            ['word' => 'CHAIN', 'translation' => 'CORRENTE', 'icon' => '⛓️'],
            ['word' => 'CHAIR', 'translation' => 'CADEIRA', 'icon' => '🪑'],
            ['word' => 'CHALK', 'translation' => 'GIZ', 'icon' => '백묵'],
            ['word' => 'CLOCK', 'translation' => 'RELÓGIO', 'icon' => '⏰'],
            ['word' => 'CLOTHES', 'translation' => 'ROUPAS', 'icon' => '👕'],
            ['word' => 'COAT', 'translation' => 'CASACO', 'icon' => '🧥'],
            ['word' => 'COIN', 'translation' => 'MOEDA', 'icon' => '🪙'],
            ['word' => 'COMB', 'translation' => 'PENTE', 'icon' => '빗'],
            ['word' => 'COMPASS', 'translation' => 'BÚSSOLA', 'icon' => '🧭'],
            ['word' => 'COMPUTER', 'translation' => 'COMPUTADOR', 'icon' => '💻'],
            ['word' => 'CROWN', 'translation' => 'COROA', 'icon' => '👑'],
            ['word' => 'CUP', 'translation' => 'XÍCARA', 'icon' => '☕'],
            ['word' => 'CURTAIN', 'translation' => 'CORTINA', 'icon' => '커튼'],
            ['word' => 'DESK', 'translation' => 'ESCRIVANINHA', 'icon' => 'โต๊ะ'],
            ['word' => 'DIAMOND', 'translation' => 'DIAMANTE', 'icon' => '💎'],
            ['word' => 'DIARY', 'translation' => 'DIÁRIO', 'icon' => '📓'],
            ['word' => 'DICE', 'translation' => 'DADOS', 'icon' => '🎲'],
            ['word' => 'DOLL', 'translation' => 'BONECA', 'icon' => '인형'],
            ['word' => 'DOOR', 'translation' => 'PORTA', 'icon' => '🚪'],
            ['word' => 'DRAWER', 'translation' => 'GAVETA', 'icon' => '서랍'],
            ['word' => 'DRESS', 'translation' => 'VESTIDO', 'icon' => '👗'],
            ['word' => 'DRILL', 'translation' => 'FURADEIRA', 'icon' => '드릴'],
            ['word' => 'DRUM', 'translation' => 'TAMBOR', 'icon' => '🥁'],
            ['word' => 'DVD', 'translation' => 'DVD', 'icon' => '📀'],
            ['word' => 'ENVELOPE', 'translation' => 'ENVELOPE', 'icon' => '✉️'],
            ['word' => 'ERASER', 'translation' => 'BORRACHA', 'icon' => '지우개'],
            ['word' => 'FAN', 'translation' => 'VENTILADOR', 'icon' => '선풍기'],
            ['word' => 'FEATHER', 'translation' => 'PENA', 'icon' => '🪶'],
            ['word' => 'FENCE', 'translation' => 'CERCA', 'icon' => '울타리'],
            ['word' => 'FLAG', 'translation' => 'BANDEIRA', 'icon' => '🚩'],
            ['word' => 'FLASHLIGHT', 'translation' => 'LANTERNA', 'icon' => '🔦'],
            ['word' => 'FLOOR', 'translation' => 'CHÃO', 'icon' => '바닥'],
            ['word' => 'FLUTE', 'translation' => 'FLAUTA', 'icon' => '플루트'],
            ['word' => 'FORK', 'translation' => 'GARFO', 'icon' => '🍴'],
            ['word' => 'FRIDGE', 'translation' => 'GELADEIRA', 'icon' => '냉장고'],
            ['word' => 'FURNITURE', 'translation' => 'MOBÍLIA', 'icon' => '🛋️'],
            ['word' => 'GAME', 'translation' => 'JOGO', 'icon' => '🎮'],
            ['word' => 'GIFT', 'translation' => 'PRESENTE', 'icon' => '🎁'],
            ['word' => 'GLASS', 'translation' => 'COPO', 'icon' => ' गिलास'],
            ['word' => 'GLASSES', 'translation' => 'ÓCULOS', 'icon' => '👓'],
            ['word' => 'GLOBE', 'translation' => 'GLOBO', 'icon' => '🌍'],
            ['word' => 'GLOVES', 'translation' => 'LUVAS', 'icon' => '🧤'],
            ['word' => 'GLUE', 'translation' => 'COLA', 'icon' => '접착제'],
            ['word' => 'GUITAR', 'translation' => 'VIOLÃO', 'icon' => '🎸'],
            ['word' => 'GUN', 'translation' => 'ARMA', 'icon' => '🔫'],
            ['word' => 'HAMMER', 'translation' => 'MARTELO', 'icon' => '🔨'],
            ['word' => 'HANDBAG', 'translation' => 'BOLSA', 'icon' => '👜'],
            ['word' => 'HANGER', 'translation' => 'CABIDE', 'icon' => '옷걸이'],
            ['word' => 'HARP', 'translation' => 'HARPA', 'icon' => '🎼'],
            ['word' => 'HAT', 'translation' => 'CHAPÉU', 'icon' => '🎩'],
            ['word' => 'HEADPHONES', 'translation' => 'FONES', 'icon' => '🎧'],
            ['word' => 'HELMET', 'translation' => 'CAPACETE', 'icon' => '⛑️'],
            ['word' => 'HORN', 'translation' => 'BUZINA', 'icon' => '뿔'],
            ['word' => 'HOSE', 'translation' => 'MANGUEIRA', 'icon' => '호스'],
            ['word' => 'INK', 'translation' => 'TINTA', 'icon' => '잉크'],
            ['word' => 'IRON', 'translation' => 'FERRO', 'icon' => '쇠'],
            // Conceitos e Ações (100)
            ['word' => 'ANGER', 'translation' => 'RAIVA', 'icon' => '😠'],
            ['word' => 'ANSWER', 'translation' => 'RESPOSTA', 'icon' => '💡'],
            ['word' => 'ART', 'translation' => 'ARTE', 'icon' => '🎨'],
            ['word' => 'ATTENTION', 'translation' => 'ATENÇÃO', 'icon' => '❗'],
            ['word' => 'BEAUTY', 'translation' => 'BELEZA', 'icon' => '💅'],
            ['word' => 'BELIEF', 'translation' => 'CRENÇA', 'icon' => '🙏'],
            ['word' => 'BIRTH', 'translation' => 'NASCIMENTO', 'icon' => '🍼'],
            ['word' => 'BRAVERY', 'translation' => 'CORAGEM', 'icon' => '🦸'],
            ['word' => 'BUSINESS', 'translation' => 'NEGÓCIO', 'icon' => '💼'],
            ['word' => 'CALM', 'translation' => 'CALMA', 'icon' => '🧘'],
            ['word' => 'CARE', 'translation' => 'CUIDADO', 'icon' => '❤️'],
            ['word' => 'CHALLENGE', 'translation' => 'DESAFIO', 'icon' => '🧗'],
            ['word' => 'CHANCE', 'translation' => 'CHANCE', 'icon' => '🎲'],
            ['word' => 'CHANGE', 'translation' => 'MUDANÇA', 'icon' => '🔄'],
            ['word' => 'CHAOS', 'translation' => 'CAOS', 'icon' => '🌀'],
            ['word' => 'CHOICE', 'translation' => 'ESCOLHA', 'icon' => '🤔'],
            ['word' => 'CLEANLINESS', 'translation' => 'LIMPEZA', 'icon' => '🧼'],
            ['word' => 'COMFORT', 'translation' => 'CONFORTO', 'icon' => '🛋️'],
            ['word' => 'COMMUNICATION', 'translation' => 'COMUNICAÇÃO', 'icon' => '💬'],
            ['word' => 'CONFUSION', 'translation' => 'CONFUSÃO', 'icon' => '❓'],
            ['word' => 'COURAGE', 'translation' => 'CORAGEM', 'icon' => '🦁'],
            ['word' => 'CREATIVITY', 'translation' => 'CRIATIVIDADE', 'icon' => '🎨'],
            ['word' => 'CULTURE', 'translation' => 'CULTURA', 'icon' => '🌍'],
            ['word' => 'CURIOSITY', 'translation' => 'CURIOSIDADE', 'icon' => '🧐'],
            ['word' => 'DANGER', 'translation' => 'PERIGO', 'icon' => '⚠️'],
            ['word' => 'DEATH', 'translation' => 'MORTE', 'icon' => '💀'],
            ['word' => 'DEFEAT', 'translation' => 'DERROTA', 'icon' => '👎'],
            ['word' => 'DELAY', 'translation' => 'ATRASO', 'icon' => '⏳'],
            ['word' => 'DESIGN', 'translation' => 'DESIGN', 'icon' => '✏️'],
            ['word' => 'DESIRE', 'translation' => 'DESEJO', 'icon' => '💫'],
            ['word' => 'DESTINY', 'translation' => 'DESTINO', 'icon' => '✨'],
            ['word' => 'DIFFERENCE', 'translation' => 'DIFERENÇA', 'icon' => '≠'],
            ['word' => 'DREAM', 'translation' => 'SONHO', 'icon' => '😴'],
            ['word' => 'DUTY', 'translation' => 'DEVER', 'icon' => '🛡️'],
            ['word' => 'EDUCATION', 'translation' => 'EDUCAÇÃO', 'icon' => '🎓'],
            ['word' => 'EFFORT', 'translation' => 'ESFORÇO', 'icon' => '💪'],
            ['word' => 'ELEGANCE', 'translation' => 'ELEGÂNCIA', 'icon' => '💎'],
            ['word' => 'ENERGY', 'translation' => 'ENERGIA', 'icon' => '⚡'],
            ['word' => 'ENTHUSIASM', 'translation' => 'ENTUSIASMO', 'icon' => '🤩'],
            ['word' => 'ENVY', 'translation' => 'INVEJA', 'icon' => '😒'],
            ['word' => 'EVIL', 'translation' => 'MAL', 'icon' => '😈'],
            ['word' => 'EVOLUTION', 'translation' => 'EVOLUÇÃO', 'icon' => '🧬'],
            ['word' => 'FAILURE', 'translation' => 'FALHA', 'icon' => '❌'],
            ['word' => 'FAITH', 'translation' => 'FÉ', 'icon' => '🙏'],
            ['word' => 'FAME', 'translation' => 'FAMA', 'icon' => '🌟'],
            ['word' => 'FEAR', 'translation' => 'MEDO', 'icon' => '😨'],
            ['word' => 'FEELING', 'translation' => 'SENTIMENTO', 'icon' => '❤️'],
            ['word' => 'FOCUS', 'translation' => 'FOCO', 'icon' => '🎯'],
            ['word' => 'FREEDOM', 'translation' => 'LIBERDADE', 'icon' => '🕊️'],
            ['word' => 'FRIENDSHIP', 'translation' => 'AMIZADE', 'icon' => '🤝'],
            ['word' => 'FUN', 'translation' => 'DIVERSÃO', 'icon' => '🎉'],
            ['word' => 'FUTURE', 'translation' => 'FUTURO', 'icon' => '🔮'],
            ['word' => 'GENEROSITY', 'translation' => 'GENEROSIDADE', 'icon' => '🤗'],
            ['word' => 'GOAL', 'translation' => 'META', 'icon' => '🥅'],
            ['word' => 'GOOD', 'translation' => 'BEM', 'icon' => '😇'],
            ['word' => 'GRACE', 'translation' => 'GRAÇA', 'icon' => '💃'],
            ['word' => 'GRATITUDE', 'translation' => 'GRATIDÃO', 'icon' => '🙏'],
            ['word' => 'GREED', 'translation' => 'GANÂNCIA', 'icon' => '🤑'],
            ['word' => 'GRIEF', 'translation' => 'LUTO', 'icon' => '😢'],
            ['word' => 'GROWTH', 'translation' => 'CRESCIMENTO', 'icon' => '📈'],
            ['word' => 'HAPPINESS', 'translation' => 'FELICIDADE', 'icon' => '😊'],
            ['word' => 'HARMONY', 'translation' => 'HARMONIA', 'icon' => '🎶'],
            ['word' => 'HATE', 'translation' => 'ÓDIO', 'icon' => '😡'],
            ['word' => 'HEALTH', 'translation' => 'SAÚDE', 'icon' => '⚕️'],
            ['word' => 'HELP', 'translation' => 'AJUDA', 'icon' => '🆘'],
            ['word' => 'HISTORY', 'translation' => 'HISTÓRIA', 'icon' => '📜'],
            ['word' => 'HOME', 'translation' => 'LAR', 'icon' => '🏡'],
            ['word' => 'HONESTY', 'translation' => 'HONESTIDADE', 'icon' => '😇'],
            ['word' => 'HOPE', 'translation' => 'ESPERANÇA', 'icon' => '✨'],
            ['word' => 'HUMOR', 'translation' => 'HUMOR', 'icon' => '😂'],
            ['word' => 'HUNGER', 'translation' => 'FOME', 'icon' => '🍔'],
            ['word' => 'IDEA', 'translation' => 'IDEIA', 'icon' => '💡'],
            ['word' => 'IMAGINATION', 'translation' => 'IMAGINAÇÃO', 'icon' => '🦄'],
            ['word' => 'INFINITY', 'translation' => 'INFINITO', 'icon' => '♾️'],
            ['word' => 'INFORMATION', 'translation' => 'INFORMAÇÃO', 'icon' => 'ℹ️'],
            ['word' => 'INTELLIGENCE', 'translation' => 'INTELIGÊNCIA', 'icon' => '🧠'],
            ['word' => 'JOY', 'translation' => 'ALEGRIA', 'icon' => '😃'],
            ['word' => 'JUSTICE', 'translation' => 'JUSTIÇA', 'icon' => '⚖️'],
            ['word' => 'KINDNESS', 'translation' => 'BONDADE', 'icon' => '😊'],
            ['word' => 'KNOWLEDGE', 'translation' => 'CONHECIMENTO', 'icon' => '📚'],
            ['word' => 'LAUGHTER', 'translation' => 'RISO', 'icon' => '🤣'],
            ['word' => 'LAW', 'translation' => 'LEI', 'icon' => '⚖️'],
            ['word' => 'LEADERSHIP', 'translation' => 'LIDERANÇA', 'icon' => '👑'],
            ['word' => 'LEARNING', 'translation' => 'APRENDIZADO', 'icon' => '📖'],
            ['word' => 'LIBERTY', 'translation' => 'LIBERDADE', 'icon' => '🗽'],
            ['word' => 'LIFE', 'translation' => 'VIDA', 'icon' => '❤️'],
            ['word' => 'LIGHT', 'translation' => 'LUZ', 'icon' => '💡'],
            ['word' => 'LOGIC', 'translation' => 'LÓGICA', 'icon' => '🧠'],
            ['word' => 'LONELINESS', 'translation' => 'SOLIDÃO', 'icon' => '😔'],
            ['word' => 'LOVE', 'translation' => 'AMOR', 'icon' => '❤️'],
            ['word' => 'LUCK', 'translation' => 'SORTE', 'icon' => '🍀'],
            ['word' => 'LUXURY', 'translation' => 'LUXO', 'icon' => '💎'],
            ['word' => 'MADNESS', 'translation' => 'LOUCURA', 'icon' => '🤪'],
            ['word' => 'MAGIC', 'translation' => 'MÁGICA', 'icon' => '✨'],
            ['word' => 'MEMORY', 'translation' => 'MEMÓRIA', 'icon' => '🧠'],
            ['word' => 'MERCY', 'translation' => 'MISERICÓRDIA', 'icon' => '🙏'],
            ['word' => 'MIRACLE', 'translation' => 'MILAGRE', 'icon' => '🌟'],
            ['word' => 'MISERY', 'translation' => 'MISÉRIA', 'icon' => '😩'],
            ['word' => 'MOMENT', 'translation' => 'MOMENTO', 'icon' => '⏳'],
            ['word' => 'MYSTERY', 'translation' => 'MISTÉRIO', 'icon' => '❓'],
            ['word' => 'NIGHTMARE', 'translation' => 'PESADELO', 'icon' => '👻'],
            // etc...
        ];

        // --- DISTRIBUIÇÃO DAS PALAVRAS COM A NOVA LÓGICA ---
        $levels = Level::all();
        $vocabularyCollection = collect($vocabulary)->shuffle();

        foreach ($levels as $level) {
            if ($vocabularyCollection->isEmpty()) {
                break;
            }

            // Define o número de palavras com base no nível atual
            $wordsPerLevel = 5;
            if ($level->level_number > 80) {
                $wordsPerLevel = 10;
            } elseif ($level->level_number > 60) {
                $wordsPerLevel = 8;
            } elseif ($level->level_number > 40) {
                $wordsPerLevel = 7;
            } elseif ($level->level_number > 20) {
                $wordsPerLevel = 6;
            }

            if ($vocabularyCollection->count() < $wordsPerLevel) {
                continue; // Pula o nível se não houver palavras suficientes
            }

            // Garante que palavras muito longas não sejam colocadas em grids pequenos
            $wordsForLevel = $vocabularyCollection->filter(function ($item) use ($level) {
                return strlen($item['word']) <= $level->grid_size;
            })->splice(0, $wordsPerLevel);

            // Remove as palavras usadas da coleção principal
            $vocabularyCollection = $vocabularyCollection->reject(function ($item) use ($wordsForLevel) {
                return $wordsForLevel->contains($item);
            });

            foreach ($wordsForLevel as $item) {
                Word::create([
                    'level_id' => $level->id,
                    'word' => $item['word'],
                    'translation' => $item['translation'],
                    'icon' => $item['icon'],
                    'image_url' => 'https://placehold.co/150x150/1f2937/fff?text=' . urlencode($item['translation'])
                ]);
            }
        }
    }
}
